#*# AutoLight Configuration File
#*# For documentation, see https://meowmeowahr.github.io/AutoLight/configuration-reference.html

sensors:
  - type: gpio
    pin: 21
  - type: gpio
    pin: 20
  - type: gpio
    pin: 7
  - type: gpio
    pin: 8
  - type: gpio
    pin: 25
  - type: gpio
    pin: 24
  - type: gpio
    pin: 16

leds:
  count: 11
  freq: 200
  fps_on : 120
  fps_off: 60

extra_leds:
  - channel: 15
    ha_name: "Closet Lights"
    ha_icon: "mdi:lightbulb"
    ha_id: "extra1"
    sensor:
      type: gpio
      pin: 11
      pullup: True
      invert: False
      bounce_time: 0.1

animations:
  blink:
    blink_hz: 2
  fade:
    fade_speed_multiplier: 0.75
  walking:
    activation_radius: 1

home_assistant:
  mqtt:
    host: "homeassistant.local"
    port: 1883
    username: "USE_ENV"
    password: "USE_ENV"
    connection_timeout: 6.0
  device:
    name: "Staircase Lighting"
    id: "sl"
  light_entity:
    name: "Main Control"
    icon: "mdi:stairs"
    id: "light_staircase"
  sensor_entities:
    naming_scheme: "Staircase Segment {0}"
    id_scheme: "stair_motion_{0}"
    device_class: "motion"
  debugging_entities:
    create_debug_entities: True
    update_rate: 15.0

logging:
  interactive_log_level: "INFO"
  regular_log_level: "INFO"
  log_file: "logger.log"
  file_logging: True
  rich_traceback: True
  
misc:
  do_banner: true
